# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import floe.proto.floe_pb2 as floe__pb2


class FloeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetModel = channel.unary_unary(
                '/floe.FloeService/GetModel',
                request_serializer=floe__pb2.FloeMessage.SerializeToString,
                response_deserializer=floe__pb2.FloeMessage.FromString,
                )
        self.ContributeModel = channel.unary_unary(
                '/floe.FloeService/ContributeModel',
                request_serializer=floe__pb2.FloeMessage.SerializeToString,
                response_deserializer=floe__pb2.FloeMessage.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/floe.FloeService/Subscribe',
                request_serializer=floe__pb2.FloeMessage.SerializeToString,
                response_deserializer=floe__pb2.FloeMessage.FromString,
                )


class FloeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ContributeModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FloeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModel,
                    request_deserializer=floe__pb2.FloeMessage.FromString,
                    response_serializer=floe__pb2.FloeMessage.SerializeToString,
            ),
            'ContributeModel': grpc.unary_unary_rpc_method_handler(
                    servicer.ContributeModel,
                    request_deserializer=floe__pb2.FloeMessage.FromString,
                    response_serializer=floe__pb2.FloeMessage.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=floe__pb2.FloeMessage.FromString,
                    response_serializer=floe__pb2.FloeMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'floe.FloeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FloeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/floe.FloeService/GetModel',
            floe__pb2.FloeMessage.SerializeToString,
            floe__pb2.FloeMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ContributeModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/floe.FloeService/ContributeModel',
            floe__pb2.FloeMessage.SerializeToString,
            floe__pb2.FloeMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/floe.FloeService/Subscribe',
            floe__pb2.FloeMessage.SerializeToString,
            floe__pb2.FloeMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
